// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfzAEH_Y0P0ISmizm6kisR2Ga3gJUWjqk',
    appId: '1:516358628876:android:0561c2cbc930425c94f029',
    messagingSenderId: '516358628876',
    projectId: 'veloria-f35fd',
    storageBucket: 'veloria-f35fd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEHyDtgYf0nah8GLg05tw494-VKA1uq2s',
    appId: '1:516358628876:ios:545b4914f3703edc94f029',
    messagingSenderId: '516358628876',
    projectId: 'veloria-f35fd',
    storageBucket: 'veloria-f35fd.firebasestorage.app',
    androidClientId: '516358628876-8ssu0dmp7dbh7dj6t4ove5gqdiiatrmh.apps.googleusercontent.com',
    iosClientId: '516358628876-cu9v2b76a2c71fk3sds7r1aai3b69lj2.apps.googleusercontent.com',
    iosBundleId: 'com.veloria.shopapp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2E2qW9f0BKXDrDzJiIxs31vLz-MZnD40',
    appId: '1:516358628876:web:2b80881f2dd2444894f029',
    messagingSenderId: '516358628876',
    projectId: 'veloria-f35fd',
    authDomain: 'veloria-f35fd.firebaseapp.com',
    storageBucket: 'veloria-f35fd.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEHyDtgYf0nah8GLg05tw494-VKA1uq2s',
    appId: '1:516358628876:ios:a6e1fe04fd86160594f029',
    messagingSenderId: '516358628876',
    projectId: 'veloria-f35fd',
    storageBucket: 'veloria-f35fd.firebasestorage.app',
    androidClientId: '516358628876-8ssu0dmp7dbh7dj6t4ove5gqdiiatrmh.apps.googleusercontent.com',
    iosClientId: '516358628876-beqh7rr8sc0jtilvt6p3k77ogcbs3js6.apps.googleusercontent.com',
    iosBundleId: 'com.example.veloria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnMiroca0M4i7legu-7vpFLiSMeZit4rU',
    appId: '1:516358628876:web:f4ba57b9c64da6d094f029',
    messagingSenderId: '516358628876',
    projectId: 'veloria-f35fd',
    authDomain: 'veloria-f35fd.firebaseapp.com',
    storageBucket: 'veloria-f35fd.firebasestorage.app',
  );
}
